import localFont from "next/font/local";
import "./globals.css";
import Header from "@/sections/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[--background] text-[--primary-text]">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
